### PR TITLE
negative weights

### PR DESCRIPTION
**Pull request by arefnel**

### CODE REVIEW

**Comment by jakejh** [comment]
Where does `getWeights()` pass the `negativeWeights` variable to the individual functions?

**Comment by jakejh** [comment]
For the prevalence method, I see a couple options if negativeWeights is TRUE: return a data.table with an additional column for person_id, or an additional column for dx_status. The latter would be more efficient, but would make later steps somewhat more complicated. What say you @arefnel ?

**Comment by jakejh** [comment]
I'm not sure our code is doing "the right thing" for loglinear, because a person could still have a negative weight even if num_occurrences is >0, right?

**Comment by arefnel** [comment]
> For the prevalence method, I see a couple options if negativeWeights is TRUE: return a data.table with an additional column for person_id, or an additional column for dx_status. The latter would be more efficient, but would make later steps somewhat more complicated. What say you @arefnel ?

One thing I just realized is that the current `getScores()` function doesn't work for negative weights since in line 82, it removes anyone without a phecode and assumes their weight was 0 later. Since age-aware weight tables have 1 row per phecode per person, we can replace the `getScores()` code with this:
```
rBig = merge(weights[, .(person_id, phecode, w)],
               diseasePhecodeMap, by =  'phecode', allow.cartesian = TRUE)
rSum = rBig[, .(score = sum(w)), keyby = .(person_id, disease_id)]
```
for the prevalence weights, if we add person_id in `getWeights()`, then there would be no need to change `getScores()`.  If we add dx_status, then we can use this code for the prevalence model in `getScores()`: 
```
  rBig = CJ(
    person_id = demos$person_id,
    phecode = intersect(diseasePhecodeMap$phecode, phecodeOccurrences$phecode))
  rBig = merge(
    rBig, unique(phecodeOccurrences[, .(person_id, phecode, dx_status = 1)]),
    by = c('person_id', 'phecode'), all.x = TRUE, allow.cartesian = TRUE)
  rBig[is.na(dx_status), dx_status := 0]
  rBig = merge(rBig, weights[, .(phecode, w, dx_status)], by = c('phecode', 'dx_status'))
  rBig[, dx_status := NULL]
  rBig = merge(rBig, diseasePhecodeMap, by = 'phecode', allow.cartesian = TRUE)
  rSum = rBig[, .(score = sum(w)), keyby = .(person_id, disease_id)]
```
So instead of adding person_id in `getWeights()` we're delaying that to `getScores()` in favor of a smaller weights table for the prevalence model. I personally think adding person_id in `getWeights()` will make things more consistent. I'm also thinking we should add a recommendation in the examples to only create weights for phecodes under disease ids the user is interested in.

**Comment by arefnel** [comment]
> I'm not sure our code is doing "the right thing" for loglinear, because a person could still have a negative weight even if num_occurrences is >0, right?

you're right! should replace all negative weights with 0 in this case?

**Comment by jakejh** [comment]
1. Good catch on `getScores()`. Agreed, let's just add `person_id` to the weights table.
2. Re loglinear, it's kind of weird either way, because whether we would set the weight to zero would then depend on the predicted number of phecodes, which isn't how the other methods work. Do we really need to keep loglinear? What if we just had prevalence, logistic, and cox?

**Comment by jakejh** [comment]
@arefnel The documentation for `getWeights()` needs to describe how the negative weights are calculated for individuals without an occurrence of the relevant phecode.

I'm increasingly in favor of removing the `phers()` function. How are you feeling about it?

**Comment by arefnel** [comment]
> @arefnel The documentation for `getWeights()` needs to describe how the negative weights are calculated for individuals without an occurrence of the relevant phecode.
> 
> I'm increasingly in favor of removing the `phers()` function. How are you feeling about it?

I agree! It's really confusing to use. It's also unclear which arguments are used for which steps. So it doesn't necessarily make the process simpler for the user and it may also encourage mistakes or people using it without an understanding of the underlying process.

**Comment by arefnel** [comment]
A couple of things: 

1) I found a mistake in the genetic association function where it didn't print certain stat columns for methods other than genotypic. Is there a way to update the phers package in cran since we have now merged the age_aware stuff to main?

2) I think we should change the getDxStatus function to accept entry_age instead of entry_date. The emerge dataset only has entry_age (not sure if that's from the original dataset or if Lisa has changed things). Regardless, I think there might be datasets that don't have dates due to privacy reasons. We're also using age in the getWeights function so this will make it more consistent.

**Comment by jakejh** [comment]
1. Just go ahead and fix the genetic association function, and it will be updated the next time we submit the package to CRAN.
2. Ok, change entry_date to entry_age or maybe just age.
3. Ok, remove the phers function along with any relevant tests and examples.

**Comment by jakejh** [comment]
I realized we also use `occurrence_age` in some places. We should probably use either that or `entry_age`, but not both.

**Comment by arefnel** [comment]
@jakejh Let me know if everything looks good and I'll go ahead and merge this branch to main.

**Comment by jakejh** [comment]
What about speedglm? Didn't you already have that working?

**Comment by arefnel** [comment]
I had created separate functions in the analysis repo to compare different glm methods. Just replaced glm with speedglm in the package.

**Review by jakejh — APPROVED** [review]

**Pull request merged**
